test hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,31 +1,52 @@
 #!/usr/bin/env bash
 
-echo "php-cs-fixer pre commit hook start"
-
 PHP_CS_FIXER="vendor/bin/php-cs-fixer"
-HAS_PHP_CS_FIXER=false
+PSALM="vendor/bin/psalm"
 
-if [ -x $PHP_CS_FIXER ]; then
-    HAS_PHP_CS_FIXER=true
-fi
-
-if $HAS_PHP_CS_FIXER; then
-    FILES=` git status --porcelain | grep -E '^[AM] +(src|tests).*\.php$' | cut -c 4- | tr '\n' ' '`
-    if [ -z "$FILES" ]
-	then
-		  echo "No php files found in commit."
-	else
-		  echo ${FILES}
-		  $PHP_CS_FIXER fix --config=.php_cs.dist --verbose ${FILES}
-		  git add ${FILES}
-	fi
-else
+if [ ! -x $PHP_CS_FIXER ]; then
     echo ""
-    echo "Please install php-cs-fixer, e.g.:"
+    echo "php-cs-fixer not found. Try:"
     echo ""
-    echo "  composer require --dev fabpot/php-cs-fixer:dev-master"
+    echo "  composer install"
     echo ""
     exit 1
 fi
 
-echo "php-cs-fixer pre commit hook finish"
+if [ ! -x $PSALM ]; then
+    echo ""
+    echo "vimeo/psalm not found. Try:"
+    echo ""
+    echo "  composer install"
+    echo ""
+    exit 1
+fi
+
+FILES=`git status --porcelain | grep -E '^[AM] +(src|tests).*\.php$' | cut -c 4- | tr '\n' ' '`
+if [ -z "$FILES" ]; then
+  echo "No php files found in commit."
+else
+  output=`php -l ${FILES}`
+  OUT=$?
+  if [ $OUT != '0' ]; then
+    echo "$output"
+    echo ""
+    echo "Please correct and recommit"
+
+    exit 1
+  fi
+
+  $PHP_CS_FIXER fix --config=.php_cs.dist ${FILES} >/dev/null 2>&1
+  git add ${FILES}
+
+#  output=`$PSALM --report=psalmCommitErrors.txt --config=psalmCommit.xml ${FILES} >/dev/null 2>&1`
+#  OUT=$?
+#  if [ $OUT != '0' ]; then
+#    echo "PSALM Failed with the following errors:"
+#    echo ""
+#    cat psalmCommitErrors.txt
+#    echo ""
+#    echo "Please correct and recommit"
+#
+#    exit 1
+#  fi
+fi
